### ISSUE TITLE
手动部署报错

### ISSUE THREAD

**Issue by Dason-zdc** [lanyulei/ferry#239]
PS E:\dason\ferry> go run main.go init -c=config/settings.dev.yml
start init
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x452095]

goroutine 1 [running]:
go.uber.org/zap.(*SugaredLogger).log(0x0, 0x5, {0x0, 0xc00004f380}, {0xc000d13cf8, 0x154aca, 0xb}, {0x0, 0x0, 0x0})
        C:/Users/gq/go/pkg/mod/go.uber.org/zap@v1.10.0/sugar.go:233 +0xf5        
go.uber.org/zap.(*SugaredLogger).Fatal(...)
        C:/Users/gq/go/pkg/mod/go.uber.org/zap@v1.10.0/sugar.go:128
ferry/pkg/logger.Fatal(...)
        E:/dason/ferry/pkg/logger/logger.go:116
ferry/tools/config.ConfigSetup({0xc00003e19b, 0xc000006018})
        E:/dason/ferry/tools/config/config.go:23 +0x11e
ferry/cmd/migrate.run()
        E:/dason/ferry/cmd/migrate/server.go:36 +0x8d
ferry/cmd/migrate.glob..func1(0x2ffaf00, {0xfff1eb, 0x2, 0x2})
        E:/dason/ferry/cmd/migrate/server.go:22 +0x17
github.com/spf13/cobra.(*Command).execute(0x2ffaf00, {0xc000106920, 0x2, 0x2})   
        C:/Users/gq/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x2ffa9c0)
        C:/Users/gq/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/gq/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887      
ferry/cmd.Execute()
        E:/dason/ferry/cmd/cobra.go:39 +0x25
main.main()
        E:/dason/ferry/main.go:8 +0x17
exit status 2

**Comment by hellorayza** [comment]
I had tried this, but useless.Can someone help me?
https://blog.csdn.net/qq_37767455/article/details/104805762

**Comment by hellorayza** [comment]
Windows users try `go run main.go init -c ./config/settings.dev.yml`
